config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts

  root 'pages#home'

  get 'orphanages-signup', to: 'orphanages#new'

  get 'orphanages-posts/:orphanage_id', to: "posts#orphanage_posts", as: "orphanage_posts"

  resources :orphanages, :except =>[:new]

  get 'orphanages-login', to: 'sessions#new_orphanage'

  post 'orphanages-login', to: 'sessions#create_orphanage'

  get 'volunteers-login', to: 'sessions#new_volunteer'

  post 'volunteers-login', to: 'sessions#create_volunteer'

  delete 'logout', to: 'sessions#destroy'

  resources :volunteers, :except =>[:new]

  get 'volunteers-signup', to: 'volunteers#new'

  get 'view-volunteering-activity', to: 'orphanage_volunteers#volunteer_activities'

  get 'view-current-volunteers', to: 'orphanage_volunteers#current_volunteers'

  get 'schedule-time', to: 'appointments#new'

  post 'schedule-time', to: 'appointments#create'

  get 'view-pending-appointments', to: 'appointments#pending_appointments'

  get 'approve-appointment/:appointment_id', to: 'appointments#approve_appointment', as: "approve_appointment"

  get 'view-approved-appointments', to: 'appointments#approved_appointments', as: "view_approved_appointments"

  delete 'cancel-appointment/:appointment_id', to: 'appointments#cancel_appointment', as: "cancel_appointment"

  get 'faqs', to: 'pages#FAQS'

  get 'eligibility_criteria', to: 'pages#eligibility_criteria'

  get 'procedures_documents_required', to: 'pages#procedures_documents_required'

  get 'what_is_Kafala', to: 'pages#what_is_kafala'

  get 'Kafala_Stories', to: 'pages#kafala_stories'

  get 'Shaymaa_Story', to: 'pages#shaymaa_story'

  get 'Yasmin_Story', to: 'pages#yasmin_story'

  get 'Sara_Story', to: 'pages#sara_story'

  get 'volunteer-options', to: 'pages#volunteer_options', as: "volunteer_options"

  get 'Fatima_Story', to: 'pages#fatima_story'

  get 'Marwa_Story', to: 'pages#marwa_story'

  get 'Hamza_Story', to: 'pages#hamza_story'

  resources :report_cases, :except => [:new, :edit, :update, :destroy, :show]

  get 'report-new-case', to: 'report_cases#new'

  post 'report-new-case', to: 'report_cases#create'

  get 'view-reported-cases', to: 'report_cases#volunteer_reported_cases', as: "view_reported_cases"

  get 'view-pending-cases', to: 'report_cases#view_pending_cases', as: "view_pending_cases"

  get 'resolved_cases', to: 'report_cases#orphanage_resolved_cases', as: "resolved_cases"

  get 'resolve_case/:case_id', to: 'report_cases#mark_as_resolved', as: "resolve_case"

  get 'accepted_cases', to: 'report_cases#orphanage_accepted_cases', as: "accepted_cases"

  get 'accept_case/:case_id', to: 'report_cases#accept_case', as: 'accept_case'

  resources :appointments, :except => [:new, :create, :destroy, :edit, :update]
  
end

app/models/orphanage.rb
class Orphanage < ApplicationRecord

    has_many :orphanage_volunteers, :dependent => :destroy

    has_many :volunteers, through: :orphanage_volunteers

    has_many :appointments, foreign_key: "orphanage_id", dependent: :destroy

    has_many :posts, foreign_key: "orphanage_id", dependent: :destroy

    before_validation :ensure_email_is_downcase

    PHONE_REGEX = /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/

    validates :name, presence: true, length: { minimum: 5, maximum: 50 }, uniqueness: {case_sensitive: false}

    validates :street_address, presence: true, length: { minimum: 5, maximum: 50 }, uniqueness: {case_sensitive: false}

    validates :bio, length: { maximum: 1500, too_long: "%{count} characters is the maximum allowed" }

    validates :phone_number,presence: true,
                 format: {with: PHONE_REGEX},
                 :length => { :minimum => 10, :maximum => 15 },
                 uniqueness: true

    validates :email, presence: true, uniqueness: true, length: {maximum:102}, format: {with: URI::MailTo::EMAIL_REGEXP} #TODO add index to anything with uniqueness

    validates :children_count,presence: true, :numericality => { :greater_than_or_equal_to => 0 }

    validates :password, :presence =>true, :confirmation =>true

    validates_confirmation_of :password

    validate :governorate_was_selected

    has_secure_password

    def governorate_was_selected
        if GOVERNORATES.nil?
            errors.add(:governorate, "governorate can't be empty")
            return 
        end
        if GOVERNORATES.include? governorate == false
            errors.add(:governorate, "governorate must be selected from given options")
        end
    end 

    def ensure_email_is_downcase
        email.downcase! if email
    end

end

app/controllers/orphanages_controller.rb
class OrphanagesController < ApplicationController

	before_action :set_orphanage, except: [:index, :new, :create]
	before_action :require_orphanage, only: [:edit, :update, :destroy]
	before_action :is_verified?, only: [:edit, :update, :destroy]
	before_action :require_same_orphanage, only: [:edit, :update, :destroy]


	def new 
		if logged_in? == false
			@orphanage = Orphanage.new
		else 
			flash[:alert] = "Your orphanage already has an account."
			redirect_to orphanages_path
		end
	end 

	def create
		@orphanage = Orphanage.new(orphanage_params)
		if @orphanage.save
			session[:orphanage_id] = @orphanage.id
			flash[:notice] = "You have signed up successfully, wait for admin approval before you can use the website functionality!"
			redirect_to posts_path
		else
			render 'new' 
		end 
	end

	def index
		@orphanages = Orphanage.where(verified: true).paginate(page: params[:page], per_page: 5)
	end

	def show
	end

	def edit
	end

	def update
		if @orphanage.update(orphanage_params)
			flash[:notice] = "Orphanage was updated successfully."
			redirect_to @orphanage
		else
			render 'edit' 
		end   
	end 

	def destroy
		@orphanage.destroy
		session[:orphanage_id] = nil
		flash[:notice] = "Account and all associated posts have been deleted successfully."
		redirect_to root_path
	end

	private

	def orphanage_params
		params.require(:orphanage).permit(:name, :email, :password, :password_confirmation, :phone_number, :children_count,
		:street_address, :governorate, :accepts_new_cases, :bio)
	end 

	def set_orphanage
		@orphanage = Orphanage.find(params[:id])
	end 

	def require_same_orphanage
		if current_user.class.name == "Orphanage"
			if current_user != @orphanage
				flash[:alert] = "This account is permitted to only edit or delete its own data."
				redirect_to orphanages_path
			end 
		else 
			flash[:alert] = "You aren't permitted to perfom this action."
			redirect_to orphanages_path
		end 
	end
end

app/helpers/orphanages_helper.rb
module OrphanagesHelper
end

app/views/orphanages/_form.html.erb
<div class="container">
   <div class="row justify-content-center">
      <div class="col-10">
         <%=render 'shared/errors', obj: @orphanage%>
         <%= form_with(model: @orphanage, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
         <div class="form-group row">
            <%= f.label :name, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of orphanage" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
               <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter Email" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
               <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter password" %>
            </div>
         </div>
        <div class="form-group row">
            <%= f.label :password_confirmation, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
               <%= f.password_field :password_confirmation, class: "form-control shadow rounded", placeholder: "Enter same password again" %>
            </div>
         </div>
          <div class="form-group row">
            <%= f.label :phone_number, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.telephone_field :phone_number, class: "form-control shadow rounded", placeholder: "Phone number of orphanage" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :children_count, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.number_field :children_count, class: "form-control shadow rounded", placeholder: "number of children in the orphanage" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :street_address, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.text_field :street_address, class: "form-control shadow rounded", placeholder: "street address of orphanage" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :governorate, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.select(:governorate, GOVERNORATES, {include_blank: "Select governorate"}, {class: 'form-control shadow rounded', required: true, selected: @set}) %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :accepts_new_cases, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.select(:accepts_new_cases, [['No',false],['Yes',true]], {include_blank: "Select State"}, {class: 'form-control shadow rounded', required: true, selected: @set})%>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :bio, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
               <%= f.text_area :bio, rows: 5, class: "form-control shadow rounded", placeholder: "Content of post" %>
            </div>
         </div>
         <div class="form-group row justify-content-center">
            <%= f.submit(@orphanage.new_record? ? "Sign up" : "Update", class: "btn btn-outline-light btn-lg") %>
         </div>
         <% end %>
      </div>
      <div class="mb3">
         <%= link_to '[ Cancel and return to posts listing ]', posts_path, class: "text-info" %>
      </div>
   </div>
</div>

app/views/orphanages/edit.html.erb
<h1 class="text-center mt-4">Edit your orphanage data</h1>
<%= render 'form' %>

app/views/orphanages/index.html.erb
<h1 class="text-center mt-4">Current Orphanages in the system</h1>
<div class="flickr_pagination">
  <%= will_paginate @orphanages, :container => false %>
</div>
<div class="container">
   <% @orphanages.each do |orphanage|%>
   <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
         <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
               <%=link_to orphanage.name, orphanage%>
            </div>
            <div class="card-body">
               <div class="card-text text-center">Verified: <%= p orphanage.verified ? "Verified" : "Not verified yet" %></div>
               <br/>
               <div class="card-text text-center">Accepts new cases: <%= p orphanage.accepts_new_cases ? "Yes." : "No." %></div>
               <br/>
               <div class="card-text text-center">Number of posts: <%= pluralize(orphanage.posts.count, "post")%></div>
               <br/>
               <div class="card-text text-center">Governorate: <%= orphanage.governorate%></div>
               <br/>
               <%if logged_in? && orphanage == current_user%>
                  <%= link_to "Edit", edit_orphanage_path(orphanage), class: "btn btn-outline-info" %>
               <%end%>
               <%= link_to "View posts made by this orphanage", orphanage_posts_path(orphanage.id), class: "btn btn-outline-info" %>
            </div>
            <div class="card-footer text-muted">
               <small>Joined <%= time_ago_in_words(orphanage.created_at) %> ago, 
               edited <%= time_ago_in_words(orphanage.updated_at) %> ago</small>
            </div>
         </div>
      </div>
   </div>
   <%end%>
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @orphanages, :container => false %>
</div>

app/views/orphanages/new.html.erb
<h1 class="text-center mt-4">Make an account for your orphanage</h1>
<%= render 'form' %>

app/views/orphanages/show.html.erb
<h1 class="text-center mt-4"><%=@orphanage.name%></h1>
<div class="container">
   <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
         <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
               <%= p @orphanage.verified ? "Verified" : "Not verified yet" %> <br/>
            </div>
            <div class="card-body">
               <div class="card-text text-left">Accepts new cases: <%= p @orphanage.accepts_new_cases ? "Yes." : "No." %></div>
               <br/>
               <div class="card-text text-left">Email: <%= @orphanage.email%></div>
               <br/>
               <div class="card-text text-left">Street Address: <%= @orphanage.street_address%></div>
               <br/>
               <div class="card-text text-left">Phone number: <%= @orphanage.phone_number%></div>
               <br/>
               <div class="card-text text-left">Children count: <%= @orphanage.children_count%></div>
               <br/>
               <div class="card-text text-left">Governorate: <%= @orphanage.governorate%></div>
               <br/>
               <div class="card-text text-left">Bio:<br/><br/><%= simple_format(@orphanage.bio)%></div>
               <br/>
               <%= link_to "View posts made by this orphanage", orphanage_posts_path(@orphanage.id), class: "btn btn-outline-info" %>
               <%if logged_in? && @orphanage == current_user%>
                  <%= link_to "Edit", edit_orphanage_path(@orphanage), class: "btn btn-outline-info" %>
                  <%= link_to "Delete", orphanage_path(@orphanage), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
               <%end%>
            </div>
            <div class="card-footer text-muted">
               <small>Created <%= time_ago_in_words(@orphanage.created_at) %> ago, 
               edited <%= time_ago_in_words(@orphanage.updated_at) %> ago</small>
            </div>
         </div>
      </div>
   </div>
</div>