config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts

  root 'pages#home'

  get 'orphanages-signup', to: 'orphanages#new'

  get 'orphanages-posts/:orphanage_id', to: "posts#orphanage_posts", as: "orphanage_posts"

  resources :orphanages, :except =>[:new]

  get 'orphanages-login', to: 'sessions#new_orphanage'

  post 'orphanages-login', to: 'sessions#create_orphanage'

  get 'volunteers-login', to: 'sessions#new_volunteer'

  post 'volunteers-login', to: 'sessions#create_volunteer'

  delete 'logout', to: 'sessions#destroy'

  resources :volunteers, :except =>[:new]

  get 'volunteers-signup', to: 'volunteers#new'

  get 'view-volunteering-activity', to: 'orphanage_volunteers#volunteer_activities'

  get 'view-current-volunteers', to: 'orphanage_volunteers#current_volunteers'

  get 'schedule-time', to: 'appointments#new'

  post 'schedule-time', to: 'appointments#create'

  get 'view-pending-appointments', to: 'appointments#pending_appointments'

  get 'approve-appointment/:appointment_id', to: 'appointments#approve_appointment', as: "approve_appointment"

  get 'view-approved-appointments', to: 'appointments#approved_appointments', as: "view_approved_appointments"

  delete 'cancel-appointment/:appointment_id', to: 'appointments#cancel_appointment', as: "cancel_appointment"

  get 'faqs', to: 'pages#FAQS'

  get 'eligibility_criteria', to: 'pages#eligibility_criteria'

  get 'procedures_documents_required', to: 'pages#procedures_documents_required'

  get 'what_is_Kafala', to: 'pages#what_is_kafala'

  get 'Kafala_Stories', to: 'pages#kafala_stories'

  get 'Shaymaa_Story', to: 'pages#shaymaa_story'

  get 'Yasmin_Story', to: 'pages#yasmin_story'

  get 'Sara_Story', to: 'pages#sara_story'

  get 'volunteer-options', to: 'pages#volunteer_options', as: "volunteer_options"

  get 'Fatima_Story', to: 'pages#fatima_story'

  get 'Marwa_Story', to: 'pages#marwa_story'

  get 'Hamza_Story', to: 'pages#hamza_story'

  resources :report_cases, :except => [:new, :edit, :update, :destroy, :show]

  get 'report-new-case', to: 'report_cases#new'

  post 'report-new-case', to: 'report_cases#create'

  get 'view-reported-cases', to: 'report_cases#volunteer_reported_cases', as: "view_reported_cases"

  get 'view-pending-cases', to: 'report_cases#view_pending_cases', as: "view_pending_cases"

  get 'resolved_cases', to: 'report_cases#orphanage_resolved_cases', as: "resolved_cases"

  get 'resolve_case/:case_id', to: 'report_cases#mark_as_resolved', as: "resolve_case"

  get 'accepted_cases', to: 'report_cases#orphanage_accepted_cases', as: "accepted_cases"

  get 'accept_case/:case_id', to: 'report_cases#accept_case', as: 'accept_case'

  resources :appointments, :except => [:new, :create, :destroy, :edit, :update]
  
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :orphanage

    validates :title, presence: true, length: { minimum: 10, maximum: 300 }

    validates :body, presence: true,  length: { minimum: 25 }

    validates :category, presence: true

    validate :category_must_be_from_list

    def category_must_be_from_list
        if category.nil?
            errors.add(:category, "category can't be empty")
            return 
        end
        if CATEGORIES.include? category == false
            errors.add(:category, "category must be selected from given options")
        end
    end 


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, except: [:index, :new, :create,:orphanage_posts, :orphanage_posts]
    before_action :require_orphanage, except: [:show, :index, :orphanage_posts]
    before_action :is_verified?, except: [:index]
    before_action :require_same_orphanage, only: [:edit, :update, :destroy]

    def show
    end 

    def index
        @posts = Post.paginate(page: params[:page], per_page: 5)
    end 

    def new
        @post = Post.new
    end 

    def create
        @post = Post.new(white_list)
        @post.orphanage = current_user
        if @post.save
            flash[:notice] = "Post was created successfully."
            redirect_to @post
        else
            render 'new'
        end
    end 

    def edit
    end

    def update 
        if @post.update(white_list)
            flash[:notice] = "Post was updated successfully."
            redirect_to @post
        else
            render 'edit' 
        end   
    end 

    def destroy 
        @post.destroy
        redirect_to posts_path
    end

    def orphanage_posts
        @posts = Post.where(orphanage_id: params[:orphanage_id]).paginate(page: params[:page], per_page: 5)
    end

    private

    def white_list
        params.require(:post).permit(:title, :category, :fulfilled, :body)
    end

    def set_post
        @post = Post.find(params[:id])
    end 

    def require_same_orphanage
        if current_user.class.name == "Orphanage"
            if current_user != @post.orphanage
                flash[:alert] = "This account is permitted to only edit or delete posts created by it."
                redirect_to @post
            end 
        else 
            flash[:alert] = "You aren't permitted to perfom this action."
            redirect_to @post
        end 
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
   <div class="row justify-content-center">
      <div class="col-10">
         <%=render 'shared/errors', obj: @post%>
         <%= form_with(model: @post, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
         <div class="form-group row">
            <%= f.label :title, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of post" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :category, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.select(:category, CATEGORIES, {include_blank: "Select Category"}, {class: 'form-control shadow rounded', required: true, selected: @set}) %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :fulfilled, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.select(:fulfilled, [['No',false],['Yes',true]], {include_blank: "Select State"}, {class: 'form-control shadow rounded', required: true, selected: @set})%>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :body, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
               <%= f.text_area :body, rows: 10, class: "form-control shadow rounded", placeholder: "Content of post" %>
            </div>
         </div>
         <div class="form-group row justify-content-center">
            <%= f.submit class: "btn btn-outline-light btn-lg" %>
         </div>
         <% end %>
      </div>
      <div class="mb3">
         <%= link_to '[ Cancel and return to posts listing ]', posts_path, class: "text-info" %>
      </div>
   </div>
</div>

app/views/posts/_post.html.erb
<div class="container">
   <%if @posts%>
      <% @posts.each do |post|%>
      <div class="row justify-content-md-center">
         <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
               <div class="card-header font-italic">
                  by  <%=link_to post.orphanage.name, orphanage_path(post.orphanage)%>
               </div>
               <div class="card-body">
                  <h5 class="card-title"><%= link_to post.title, post_path(post), class: "text-success" %></h5>
                  <h6>Category: <%=post.category%>.  Status: <%= p post.fulfilled ? "Closed." : "Open." %></h6>
                  <p class="card-text"><%= truncate(post.body, length: 100) %></p>
                  <%= link_to "View", post_path(post), class: "btn btn-outline-success" %>
                  <% if logged_in? && post.orphanage == current_user%>
                     <%= link_to "Edit", edit_post_path(post), class: "btn btn-outline-info" %>
                     <%= link_to "Delete", post_path(post), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
                  <%end%>
               </div>
               <div class="card-footer text-muted">
                  <small>Created <%= time_ago_in_words(post.created_at) %> ago, 
                  edited <%= time_ago_in_words(post.updated_at) %> ago</small>
               </div>
            </div>
         </div>
      </div>
      <% end %>
   <%end%>
</div>

app/views/posts/edit.html.erb
  <h1 class="text-center mt-4">Edit post</h1>
  <%= render 'form' %>

app/views/posts/index.html.erb
<h1 class="text-center mt-4">Listing all Posts</h1>
<div class="flickr_pagination">
   <%= will_paginate @posts, :container => false %>
</div>
<%= render 'post' %>
<div class="flickr_pagination mb-4">
   <%= will_paginate @posts, :container => false %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center mt-4">Create a new post</h1>
<%= render 'form' %>

app/views/posts/orphanage_posts.html.erb
<h1 class="text-center mt-4">Listing all Posts belonging to Orphanage</h1>
<div class="flickr_pagination">
  <%= will_paginate @posts, :container => false %>
</div>
<%= render 'post'%>
<div class="flickr_pagination">
  <%= will_paginate @posts, :container => false %>
</div>

app/views/posts/show.html.erb
<h1 class="text-center mt-4"><%=@post.title%></h1>
<div class="container">
   <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
         <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
            by  <%=link_to @post.orphanage.name, orphanage_path(@post.orphanage)%><br/>
            </div>
            <div class="card-body">
               <h6>Category: <%=@post.category%>.  Status: <%= p @post.fulfilled ? "Closed." : "Open." %></h6>
               <div class="card-text text-left"><%= simple_format(@post.body)%></div>
               <%if logged_in? && @post.orphanage == current_user%>
                  <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-info" %>
                  <%= link_to "Delete", post_path(@post), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
               <%end%>
            </div>
            <div class="card-footer text-muted">
               <small>Created <%= time_ago_in_words(@post.created_at) %> ago, 
               edited <%= time_ago_in_words(@post.updated_at) %> ago</small>
            </div>
         </div>
      </div>
   </div>
</div>