config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts

  root 'pages#home'

  get 'orphanages-signup', to: 'orphanages#new'

  get 'orphanages-posts/:orphanage_id', to: "posts#orphanage_posts", as: "orphanage_posts"

  resources :orphanages, :except =>[:new]

  get 'orphanages-login', to: 'sessions#new_orphanage'

  post 'orphanages-login', to: 'sessions#create_orphanage'

  get 'volunteers-login', to: 'sessions#new_volunteer'

  post 'volunteers-login', to: 'sessions#create_volunteer'

  delete 'logout', to: 'sessions#destroy'

  resources :volunteers, :except =>[:new]

  get 'volunteers-signup', to: 'volunteers#new'

  get 'view-volunteering-activity', to: 'orphanage_volunteers#volunteer_activities'

  get 'view-current-volunteers', to: 'orphanage_volunteers#current_volunteers'

  get 'schedule-time', to: 'appointments#new'

  post 'schedule-time', to: 'appointments#create'

  get 'view-pending-appointments', to: 'appointments#pending_appointments'

  get 'approve-appointment/:appointment_id', to: 'appointments#approve_appointment', as: "approve_appointment"

  get 'view-approved-appointments', to: 'appointments#approved_appointments', as: "view_approved_appointments"

  delete 'cancel-appointment/:appointment_id', to: 'appointments#cancel_appointment', as: "cancel_appointment"

  get 'faqs', to: 'pages#FAQS'

  get 'eligibility_criteria', to: 'pages#eligibility_criteria'

  get 'procedures_documents_required', to: 'pages#procedures_documents_required'

  get 'what_is_Kafala', to: 'pages#what_is_kafala'

  get 'Kafala_Stories', to: 'pages#kafala_stories'

  get 'Shaymaa_Story', to: 'pages#shaymaa_story'

  get 'Yasmin_Story', to: 'pages#yasmin_story'

  get 'Sara_Story', to: 'pages#sara_story'

  get 'volunteer-options', to: 'pages#volunteer_options', as: "volunteer_options"

  get 'Fatima_Story', to: 'pages#fatima_story'

  get 'Marwa_Story', to: 'pages#marwa_story'

  get 'Hamza_Story', to: 'pages#hamza_story'

  resources :report_cases, :except => [:new, :edit, :update, :destroy, :show]

  get 'report-new-case', to: 'report_cases#new'

  post 'report-new-case', to: 'report_cases#create'

  get 'view-reported-cases', to: 'report_cases#volunteer_reported_cases', as: "view_reported_cases"

  get 'view-pending-cases', to: 'report_cases#view_pending_cases', as: "view_pending_cases"

  get 'resolved_cases', to: 'report_cases#orphanage_resolved_cases', as: "resolved_cases"

  get 'resolve_case/:case_id', to: 'report_cases#mark_as_resolved', as: "resolve_case"

  get 'accepted_cases', to: 'report_cases#orphanage_accepted_cases', as: "accepted_cases"

  get 'accept_case/:case_id', to: 'report_cases#accept_case', as: 'accept_case'

  resources :appointments, :except => [:new, :create, :destroy, :edit, :update]
  
end

app/controllers/report_cases_controller.rb
class ReportCasesController < ApplicationController

    before_action :logged_in?
    before_action :require_volunteer, only: [:new, :create, :volunteer_reported_cases]
    before_action :require_orphanage, only: [:view_pending_cases, :accept_case, :mark_as_resolved]
    before_action :is_verified?, only: [:view_pending_cases, :accept_case, :mark_as_resolved, :orphanage_accepted_cases, :orphanage_resolved_cases]
    before_action :set_case, only: [:accept_case, :mark_as_resolved]
    
    def new 
        @case = ReportCase.new
    end 

    def create 
        @case = ReportCase.new(set_params)
        @case.volunteer = current_user
        if @case.save
            flash[:notice] = "Case was reported successfully, you could check whether an orphanage accepted the case through reported cases page."
            redirect_to view_reported_cases_path
        else  
            render 'new'
        end
    end 

    def volunteer_reported_cases
        @cases = current_user.report_cases.paginate(page: params[:page], per_page: 5)
    end 

    def view_pending_cases
        if current_user.accepts_new_cases
            @cases = ReportCase.where(case_accepted: false).paginate(page: params[:page], per_page: 5)
        else 
            flash[:alert] = "Edit your account so that it can accept new cases in order to view this page."
            redirect_to view_pending_cases_path
        end 
    end 

    def orphanage_accepted_cases
        @cases = ReportCase.where(orphanage_id: current_user.id, case_resolved: false).paginate(page: params[:page], per_page: 5)   
    end 

    def orphanage_resolved_cases
        @cases = ReportCase.where(orphanage_id: current_user.id, case_resolved: true).paginate(page: params[:page], per_page: 5)   
    end

    def accept_case 
        @case.case_accepted = true;
        @case.orphanage_id = current_user.id
        if @case.save
            flash[:notice] = "Your orphanage has accepted the case and it will be added to the accepted cases page."
            redirect_to accepted_cases_path
        else 
            flash[:alert] = "Case couldn't be accepted."
            redirect_to view_pending_cases_path
        end
    end 

    def mark_as_resolved
       if @case.orphanage_id == current_user.id 
            @case.case_resolved = true
            @case.save
            flash[:notice] = "Case was marked as resolved "
            redirect_to resolved_cases_path
       else 
            flash[:alert] = "Case couldn't be accepted."
            redirect_to accepted_cases_path
       end
    end

    private 

    def set_params
        params.require(:report_case).permit(:name, :street_address, :governorate, :approximate_age, :health_state, :description, :note)
    end 

    def set_case
        @case = ReportCase.find(params[:case_id]) 
    end
end

app/helpers/report_cases_helper.rb
module ReportCasesHelper
end

app/views/report_cases/_case.html.erb
<div class="container">
   <%@cases.each do |reported_case| %>
   <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
         <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
               Reported by  <%=link_to reported_case.volunteer.first_name+" "+reported_case.volunteer.last_name, volunteer_path(reported_case.volunteer)%>
            </div>
            <div class="card-body">
               <div class="card-text text-left">Case State: <%= p reported_case.case_resolved ? "Resolved." : "Open." %></div>
               <br/>
               <%if reported_case.case_accepted%>
                  <%if Orphanage.find_by(id: reported_case.orphanage_id)%>
                     <%o = Orphanage.find_by(id: reported_case.orphanage_id)%>
                     <div class="card-text text-left">Case accepted by: <%=link_to o.name, orphanage_path(o) %></div>
                     <br/>
                  <%else%>
                     <div class="card-text text-left">Case accepted by: (Orphanage no longer exists on the system)</div>
                     <br/>
                  <%end%>
               <%end%>
               <div class="card-text text-left">Child name: <%= reported_case.name == "" ? "Non provided" : reported_case.name %></div>
               <br/>
               <div class="card-text text-left">Street Address: <%= reported_case.street_address %></div>
               <br/>
               <div class="card-text text-left">Governorate: <%= reported_case.governorate%></div>
               <br/>
               <div class="card-text text-left">Approximate age: <%= reported_case.approximate_age%></div>
               <br/>
               <div class="card-text text-left">Health State: <%= reported_case.health_state%></div>
               <br/>
               <div class="card-text text-left">Description: <%= reported_case.description%></div>
               <br/>
               <%if reported_case.note != ""%>
               <div class="card-text text-left">Notes: <%=reported_case.note%></div>
               <%end%>
               <%if reported_case.case_accepted == false && current_user.class.name == "Orphanage"%>
               <%= link_to "Accept Case", accept_case_path(reported_case.id), class: "btn btn-outline-info" %>
               <%elsif reported_case.case_accepted && !reported_case.case_resolved && current_user == Orphanage.find_by(id: reported_case.orphanage_id) %>
               <%= link_to "Resolve Case", resolve_case_path(reported_case.id), class: "btn btn-outline-info" %>
               <%end%>
            </div>
            <div class="card-footer text-muted">
               <small>Created <%= time_ago_in_words(reported_case.created_at) %> ago, 
               edited <%= time_ago_in_words(reported_case.updated_at) %> ago</small>
            </div>
         </div>
      </div>
   </div>
   <%end%>
</div>

app/views/report_cases/new.html.erb
<h1 class="text-center mt-4">Report a case of a child in need</h1>
<p class="text-center mt-4">*Please note that a case can't be edited once created so review information before submitting</p>
<div class="container">
   <div class="row justify-content-center">
      <div class="col-10">
         <%=render 'shared/errors', obj: @case%>
         <%= form_with(scope: :report_case, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
         <div class="form-group row">
            <%= f.label :name, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of child if known" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :street_address, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.text_field :street_address, class: "form-control shadow rounded", placeholder: "location where child was found" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :governorate, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.select(:governorate, GOVERNORATES, {include_blank: "Select governorate"}, {class: 'form-control shadow rounded', required: true, selected: @set}) %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :approximate_age, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.text_field :approximate_age, class: "form-control shadow rounded", placeholder: "approximate age of child" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :health_state, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
               <%= f.text_area :health_state, rows: 2, class: "form-control shadow rounded", placeholder: "health state of child" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :description, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
               <%= f.text_area :description, rows: 3, class: "form-control shadow rounded", placeholder: "description of child" %>
            </div>
         </div>
         <div class="form-group row">
            <%= f.label :note, class: "col-2 col-form-label text-light" %>
            <div class="col-10"> 
               <%= f.text_area :note, rows: 3, class: "form-control shadow rounded", placeholder: "Leave a note for the orphanage in case you are taking further actions" %>
            </div>
         </div>
         <div class="form-group row justify-content-center">
            <%= f.submit(:Submit, class: "btn btn-outline-light btn-lg") %>
         </div>
         <% end %>
      </div>
      <div class="mb3">
         <br/><%= link_to '[ Cancel and return to posts listing ]', posts_path, class: "text-info" %>
      </div>
   </div>
</div>

app/views/report_cases/orphanage_accepted_cases.html.erb
<h1 class="text-center mt-4">Cases Accepted by your account</h1>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>
<%= render 'case'%>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>

app/views/report_cases/orphanage_resolved_cases.html.erb
<h1 class="text-center mt-4">Cases Resolved by your account</h1>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>
<%= render 'case'%>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>

app/views/report_cases/view_pending_cases.html.erb
<h1 class="text-center mt-4">Cases pending acceptance</h1>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>
<%= render 'case'%>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>

app/views/report_cases/volunteer_reported_cases.html.erb
<h1 class="text-center mt-4">Cases reported by your account</h1>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>
<%= render 'case'%>
<div class="flickr_pagination">
   <%= will_paginate @cases, :container => false %>
</div>