config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :posts

  root 'pages#home'

  get 'orphanages-signup', to: 'orphanages#new'

  get 'orphanages-posts/:orphanage_id', to: "posts#orphanage_posts", as: "orphanage_posts"

  resources :orphanages, :except =>[:new]

  get 'orphanages-login', to: 'sessions#new_orphanage'

  post 'orphanages-login', to: 'sessions#create_orphanage'

  get 'volunteers-login', to: 'sessions#new_volunteer'

  post 'volunteers-login', to: 'sessions#create_volunteer'

  delete 'logout', to: 'sessions#destroy'

  resources :volunteers, :except =>[:new]

  get 'volunteers-signup', to: 'volunteers#new'

  get 'view-volunteering-activity', to: 'orphanage_volunteers#volunteer_activities'

  get 'view-current-volunteers', to: 'orphanage_volunteers#current_volunteers'

  get 'schedule-time', to: 'appointments#new'

  post 'schedule-time', to: 'appointments#create'

  get 'view-pending-appointments', to: 'appointments#pending_appointments'

  get 'approve-appointment/:appointment_id', to: 'appointments#approve_appointment', as: "approve_appointment"

  get 'view-approved-appointments', to: 'appointments#approved_appointments', as: "view_approved_appointments"

  delete 'cancel-appointment/:appointment_id', to: 'appointments#cancel_appointment', as: "cancel_appointment"

  get 'faqs', to: 'pages#FAQS'

  get 'eligibility_criteria', to: 'pages#eligibility_criteria'

  get 'procedures_documents_required', to: 'pages#procedures_documents_required'

  get 'what_is_Kafala', to: 'pages#what_is_kafala'

  get 'Kafala_Stories', to: 'pages#kafala_stories'

  get 'Shaymaa_Story', to: 'pages#shaymaa_story'

  get 'Yasmin_Story', to: 'pages#yasmin_story'

  get 'Sara_Story', to: 'pages#sara_story'

  get 'volunteer-options', to: 'pages#volunteer_options', as: "volunteer_options"

  get 'Fatima_Story', to: 'pages#fatima_story'

  get 'Marwa_Story', to: 'pages#marwa_story'

  get 'Hamza_Story', to: 'pages#hamza_story'

  resources :report_cases, :except => [:new, :edit, :update, :destroy, :show]

  get 'report-new-case', to: 'report_cases#new'

  post 'report-new-case', to: 'report_cases#create'

  get 'view-reported-cases', to: 'report_cases#volunteer_reported_cases', as: "view_reported_cases"

  get 'view-pending-cases', to: 'report_cases#view_pending_cases', as: "view_pending_cases"

  get 'resolved_cases', to: 'report_cases#orphanage_resolved_cases', as: "resolved_cases"

  get 'resolve_case/:case_id', to: 'report_cases#mark_as_resolved', as: "resolve_case"

  get 'accepted_cases', to: 'report_cases#orphanage_accepted_cases', as: "accepted_cases"

  get 'accept_case/:case_id', to: 'report_cases#accept_case', as: 'accept_case'

  resources :appointments, :except => [:new, :create, :destroy, :edit, :update]
  
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; CODE_Challenge</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <%= link_to "CODE Challenge", root_path, class: "navbar-brand", id: "logo"%>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
   <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
         <li class="nav-item">
            <%= link_to "Orphanages", orphanages_path, class: "nav-link"%>
         </li>
         <%if logged_in? == false%>
         <%=link_to "Sign up as orphanage", orphanages_signup_path, class: "nav-link"%>
         <%=link_to "Register as a volunteer", volunteers_signup_path, class: "nav-link"%>
         <%end%>
         <%if logged_in? && current_user.class.name == "Orphanage"%>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Posts
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%if logged_in? && current_user.class.name == "Orphanage" && current_user.verified%>
               <%=link_to "Create new post", new_post_path, class: "dropdown-item"%>
               <%end%>
               <%=link_to "View posts", posts_path, class: "dropdown-item"%>
            </div>
         </li>
         <%else%>
         <%=link_to "View posts", posts_path, class: "nav-link"%>
         <%end%>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Kafala Section
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to 'What is Kafala?', '/what_is_Kafala', class: "dropdown-item"%>
               <%= link_to 'Kafala Stories', '/Kafala_Stories', class: "dropdown-item"%>
               <%= link_to 'Eligibility Criteria', '/eligibility_criteria', class: "dropdown-item"%>
               <%= link_to 'Procedures and documents required', '/procedures_documents_required', class: "dropdown-item"%>
               <%= link_to 'Popular Questions regarding Kafala', '/faqs', class: "dropdown-item"%>
            </div>
         </li>
         <%if logged_in?%>
         <li class="nav-item dropdown">
            <%if current_user.class.name == "Orphanage" && current_user.verified%>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile [<%=current_user.name%>]
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to "View the orphanage profile", orphanage_path(current_user), class: "dropdown-item"%>
               <%=link_to "Edit the orphanage profile", edit_orphanage_path(current_user), class: "dropdown-item"%>
               <%=link_to "Delete the orphanage profile", orphanage_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Appointments
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to "View your volunteers", view_current_volunteers_path, class: "dropdown-item"%>
               <%=link_to "View pending appointments", view_pending_appointments_path, class: "dropdown-item"%>
               <%=link_to "View approved appointments", view_approved_appointments_path, class: "dropdown-item" %>
            </div>
         </li>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Manage Reported Cases 
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%if current_user.accepts_new_cases%>
               <%=link_to "View pending cases", view_pending_cases_path, class: "dropdown-item"%>
               <%end%>
               <%=link_to "View accepted cases", accepted_cases_path, class: "dropdown-item"%>
               <%=link_to "View resolved cases", resolved_cases_path, class: "dropdown-item"%>
            </div>
         </li>
         <% elsif current_user.class.name == "Volunteer" %>
         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Profile [<%=current_user.first_name%>]
         </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%=link_to "View your profile", volunteer_path(current_user), class: "dropdown-item"%>
            <%=link_to "Edit your profile", edit_volunteer_path(current_user), class: "dropdown-item"%>
            <%=link_to "Delete your profile", volunteer_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?"} %>
         </div>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Appointments
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to "Schedule an appointment", schedule_time_path, class: "dropdown-item"%>
               <%=link_to "View your volunteering locations", view_volunteering_activity_path, class: "dropdown-item"%>
               <%=link_to "View approved appointments", view_approved_appointments_path, class: "dropdown-item" %>
            </div>
         </li>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Report found child 
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to "Report a case", '/report-new-case', class: "dropdown-item"%>
               <%=link_to "View your reported cases", view_reported_cases_path, class: "dropdown-item"%>
            </div>
         </li>
         </li>
         <%end%>
         <li class="nav-item">
            <%= link_to 'Log out', logout_path, class: "nav-link", method: :delete %>
         </li>
         <%else%>
         <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Login
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
               <%=link_to 'Log in as orphanage', orphanages_login_path, class: "dropdown-item"%>
               <%= link_to 'Log in as volunteer', volunteers_login_path, class: "dropdown-item"%>
            </div>
         </li>
         <%end%>
      </ul>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CODEChallengeMenna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content">
      <%= render 'layouts/messages'%> 
      <%= yield %>
    </div>
    <%=render 'layouts/footer'%>
  </body>
</html>